cameras:
  - id: 0
    name: "Camera 0"
    source: "http://192.168.0.105:8080/video"
    enabled: true
    resolution:
      width: 640
      height: 480
    fps: 30
    rotate: 0

  - id: 1
    name: "Camera 1"
    source: 1
    enabled: true
    resolution:
      width: 1280
      height: 720
    fps: 30
    rotate: 0
